### ISSUE TITLE
[Bug]when cargo install, error 

### ISSUE THREAD

**Issue by lemonwuhao** [AleoHQ/snarkOS#2090]
## 🐛 Bug Report

root@iZbp1f9wb88dbk7yoac47qZ:/home/aleo/snarkOS# cargo install --path .
error: failed to load manifest for workspace member `/home/aleo/snarkOS/account`

Caused by:
  failed to parse manifest at `/home/aleo/snarkOS/account/Cargo.toml`

Caused by:
  feature `workspace-inheritance` is required

  The package requires the Cargo feature called `workspace-inheritance`, but that feature is not stabilized in this version of Cargo (1.61.0).
  Consider adding `cargo-features = ["workspace-inheritance"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance for more information about the status of this feature.

## Your Environment

- 
- 
-

**Comment by howardwu** [comment]
The Rust MSRV is 1.64 (see README).

To solve, run `rustup update` in Terminal.

**Comment by lemonwuhao** [comment]
> 
I install Rust by cmd "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"

but Rust version is:

root@kuboworker:/mnt/e/aleo# rustc --version
rustc 1.61.0

**Comment by kubowoo** [comment]
> The Rust MSRV is 1.64 (see README).
> 
> To solve, run `rustup update` in Terminal.

@howardwu 

root@iZbp1f9wb88dbk7yoac47qZ:/home/aleo/snarkOS# cargo --version
**_cargo 1.65.0_** (4bc8f24d3 2022-10-20)
root@iZbp1f9wb88dbk7yoac47qZ:/home/aleo/snarkOS# rustc --version
_**rustc 1.65.0**_ (897e37553 2022-11-02)
root@iZbp1f9wb88dbk7yoac47qZ:/home/aleo/snarkOS# systemctl status rc-local.service
● rc-local.service - /etc/rc.local Compatibility
     Loaded: loaded (/etc/systemd/system/rc-local.service; enabled-runtime; vendor preset: enabled)
    Drop-In: /usr/lib/systemd/system/rc-local.service.d
             └─debian.conf
     Active: activating (start) since Thu 2022-11-24 17:56:36 CST; 13min ago
       Docs: man:systemd-rc-local-generator(8)
Cntrl PID: 947 (rc.local)
      Tasks: 3 (limit: 9479)
     Memory: 2.9M
     CGroup: /system.slice/rc-local.service
             ├─947 /bin/sh /etc/rc.local start
             ├─948 /bin/bash /home/aleo/snarkOS/test.sh
             └─987 sleep 1800

Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]: error: failed to load manifest for workspace member `/home/aleo/snarkOS/account`
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]: Caused by:
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]:   **_failed to parse manifest at `/home/aleo/snarkOS/account/Cargo.toml`_**
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]: Caused by:
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]:   **_feature `workspace-inheritance` is required_**
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]:   The package requires the Cargo feature called `workspace-inheritance`, but that feature is not stabilized in this version of **_Cargo (1.61.0_**).
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]:   Consider adding `cargo-features = ["workspace-inheritance"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
Nov 24 17:56:36 iZbp1f9wb88dbk7yoac47qZ rc.local[954]:   See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance for more information about the status of this feature.
Nov 24 17:56:38 iZbp1f9wb88dbk7yoac47qZ rc.local[977]: From https://github.com/AleoHQ/snarkOS
Nov 24 17:56:38 iZbp1f9wb88dbk7yoac47qZ rc.local[977]:    52a648e8d..5ffa7e635  sync       -> origin/sync
