### ISSUE TITLE
failed to compile `snarkos v2.0.2

### ISSUE THREAD

**Issue by lc12345670** [AleoHQ/snarkOS#2161]
./build_ubuntu.sh  error：
error: failed to compile `snarkos v2.0.2 (/root/snarkOS)`, intermediate artifacts can be found at `/root/snarkOS/target

**Comment by ljedrz** [comment]
Please provide more information:
- what is your operating system?
- what's the top commit of the build you're attempting?
- what's your output of `rustc --version`?
- what was the full error output?

**Comment by uranuschen365** [comment]
I have same problem，this is my error log：
error[E0599]: no method named `find_deployment_id` found for reference `&TransactionStore<N, <C as snarkvm::prelude::ConsensusStorage<N>>::TransactionStorage>` in the current scope
  --> node/ledger/src/find.rs:43:37
   |
43 |         self.vm.transaction_store().find_deployment_id(program_id)
   |                                     ^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `get_deployment`

error[E0599]: no method named `find_transaction_id` found for reference `&TransactionStore<N, <C as snarkvm::prelude::ConsensusStorage<N>>::TransactionStorage>` in the current scope
  --> node/ledger/src/find.rs:48:37
   |
48 |         self.vm.transaction_store().find_transaction_id(transition_id)
   |                                     ^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `find_transaction_id_from_program_id`

   Compiling headers-core v0.2.0
   Compiling librocksdb-sys v0.8.3+7.4.4
For more information about this error, try `rustc --explain E0599`.
error: could not compile `snarkos-node-ledger` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.0.2 (/root/snarkOS)`, intermediate artifacts can be found at `/root/snarkOS/target`

my rust version is 1.67.1
rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by ljedrz** [comment]
Ok, so this one is just a snarkVM dependency mismatch; you can remove the `Cargo.lock` file and then run `cargo build --release`, or wait until https://github.com/AleoHQ/snarkOS/pull/2238 gets merged.

**Comment by uranuschen365** [comment]
Thanks!

**Comment by matthprost** [comment]
Hello!

I have the same issue even after deleting `Cargo.lock` and running `cargo build --release`:

```sh
$ ~/snarkOS# rm Cargo.lock

$ ~/snarkOS# cargo build --release
    Updating crates.io index
   Compiling snarkos v2.0.2 (/root/snarkOS)
   Compiling librocksdb-sys v0.8.3+7.4.4
   Compiling snarkos-node-ledger v2.0.2 (/root/snarkOS/node/ledger)
   Compiling snarkos-node-router v2.0.2 (/root/snarkOS/node/router)
   Compiling rocksdb v0.19.0
error[E0599]: no method named `find_deployment_id` found for reference `&TransactionStore<N, <C as snarkvm::prelude::ConsensusStorage<N>>::TransactionStorage>` in the current scope
  --> node/ledger/src/find.rs:43:37
   |
43 |         self.vm.transaction_store().find_deployment_id(program_id)
   |                                     ^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `get_deployment`

error[E0599]: no method named `find_transaction_id` found for reference `&TransactionStore<N, <C as snarkvm::prelude::ConsensusStorage<N>>::TransactionStorage>` in the current scope
  --> node/ledger/src/find.rs:48:37
   |
48 |         self.vm.transaction_store().find_transaction_id(transition_id)
   |                                     ^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `find_transaction_id_from_program_id`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `snarkos-node-ledger` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

$ ~/snarkOS# rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

**Comment by ljedrz** [comment]
Closing, as the aforementioned fixing PR had been merged.
