### ISSUE TITLE
[Bug] A malicous leader validator(or client) could send **a hard fork block** to other nodes cause them to hard fork

### ISSUE THREAD

**Issue by feezybabee** [AleoHQ/snarkOS#2898]
# https://hackerone.com/reports/2274930

## Summary

A malicous leader validator(or client) could send **a hard fork block** to other nodes cause them on a hard fork chain.

The root cause is  `check_next_block` doesn't check the `Block::Authoriy(Subdag)`, and we don't have enough  information to check the `block.authority.subdag.leader_certificate` is actually committed by all the nodes.

In addition,
The subdag may be completely invalid, since we only check the leader certificate is belongs to committee, the leader certificate itself may be not available or quorum.

## Proof-of-Concept (PoC)

The maclious validator could always hold the `batch_certificate` and never send to other nodes. And the attacker could  use `batch_certificate` to create a dag to construct a hard fork block and block locators.

If other nodes doesn't connect to enough valid validators, they will send `BlockRequest` to the attacker, and when the attacker receive `BlockResponse` from other nodes, just send the hard fork block to them. 

## Fix
At least f + 1 validators are needed to check the consistent of blocks

## Impact
Cause chain hard fork and halt the block production

**Comment by ghostant-1017** [comment]
Hi @vicsn, 
A working POC to demonstrate this vulnerability here.

Check this branch of snarkos: https://github.com/ghostant-1017/snarkOS/tree/attack/hard-fork

1.Start 4 validator nodes

```
./devnet.sh
```

2.Assume the validator 0 is the malicious one

```shell
# use the branch above to build `snarkos-patched`
./snarkos-patched start --nodisplay --dev 0 --dev-num-validators 4 --validator
```

3.Start a client node

```Shell
snarkos start --client --dev 5 --nodisplay --verbosity 3

# if we want to reproduce more quickly, we can let the client only connect the validator 0
# snarkos start --client --dev 5 --peers 127.0.0.1:4130 --nodisplay --verbosity 3 
```

4.Check the client logs:

```
2024-01-08T08:49:38.053383Z  WARN snarkos_node_sync::block_sync: The next block (11) is invalid - Failed to speculate on transactions - Failed to post-ratify - Next round 22 must be greater than current round 22
```

**Comment by ghostant-1017** [comment]
Remove (or client), this only works when the malicious node is a validator.

**Comment by niklaslong** [comment]
I've been able to reproduce this issue with a client (on the receiving end, i.e. step 3 in your instructions). Does this bug affect validators as well? They check sync state differently.

**Comment by ghostant-1017** [comment]
> I've been able to reproduce this issue with a client (on the receiving end, i.e. step 3 in your instructions). Does this bug affect validators as well? They check sync state differently.

Yes before this pr merged. https://github.com/AleoHQ/snarkOS/pull/3012

**Comment by howardwu** [comment]
This attack technically doesn't work for validators, because they do not blindly accept recent blocks (within GC depth). Instead, they replay all certificates through the BFT to construct the blocks themselves. It would be impossible to compromise the subdag without compromising at least 2f+1 signatures from the committee lookback set.

This is technically a possible attack vector for clients however, and so a redundancy factor is ideal for guarding against this, or to connect to trusted peers only when booting up your node (and filling all open slots with only trusted peers).

**Comment by ghostant-1017** [comment]
> This attack technically doesn't work for validators, because they do not blindly accept recent blocks (within GC depth). Instead, they replay all certificates through the BFT to construct the blocks themselves. It would be impossible to compromise the subdag without compromising at least 2f+1 signatures from the committee lookback set.
> 
> This is technically a possible attack vector for clients however, and so a redundancy factor is ideal for guarding against this, or to connect to trusted peers only when booting up your node (and filling all open slots with only trusted peers).

Originally worked for validators, https://github.com/AleoHQ/snarkOS/pull/3012 has fixed it.

**Comment by howardwu** [comment]
Marking as resolved, thanks @ghostant-1017 !

**Comment by ghostant-1017** [comment]
@howardwu The  attack still works for client, should we create another issue for it?

**Comment by howardwu** [comment]
Do you know if there is any real mitigations for clients?

In Bitcoin, I know this was an acknowledge vulnerability and even when they switched to header-first syncing, they relied on you trusting your peers to be honest.

The only known solution is to hardcode bootstrap nodes as the default.

**Comment by ghostant-1017** [comment]
In Bitcoin, the node could revert if it finds a heavier chain, since it
could always check the block is valid correctly.
When we check the block, we need check the subdag of the block, so the
committee is needed to ensure it.

**Comment by howardwu** [comment]
Correct, thats for the fork-choice rule.

But for long-range syncing (i.e. greater than 1 week of blocks), which is also similar to the case we are talking about here, my understanding is that Bitcoin will defer to trusted peers to bootstrap with. Meaning you can have some redundancy (as we support too), however there isn't more of a guarantee that can be provided because this is a fundamental root of trust concern.

**Comment by ghostant-1017** [comment]
@howardwu 
Right, long-range syncing in Bitcoin will defer to trusted peers.
The problem here is, why don't we pass the committee as a parameter when `check_next_block` to ensure the subdag is a valid authority?  If so, we don't need redundancy.
The attack here is that, the leader of a round could generate a block which contains an invalid subdag( BatchCertificates signed by **ANY** address **NOT** in the committee)
