### ISSUE TITLE
[Bug] Transaction result not output to console on snarkos developer deploy command

### ISSUE THREAD

**Issue by arosboro** [AleoHQ/snarkOS#2957]
## 🐛 Bug Report

I would typically expect to know the result of my tx when seeing "Successfully broadcast deployment".  However as it stands it says that and mysteriously my tx never appears anywhere useful.

## Steps to Reproduce

zk_deck_shuffle % snarkos developer deploy "zk_deck_shuffle_v0_0_1.aleo" --path "./build" --private-key "${PRIVATE_KEY}" --query "https://api.explorer.aleo.org/v1" --broadcast "https://api.explorer.aleo.org/v1/testnet3/transaction/broadcast" --priority-fee 0

Gives indication of sucessful broadcast, but that's where it ends.

## Expected Behavior

https://developer.aleo.org/testnet/public_endpoints/transaction_broadcast

The documentation says there is a result code.  Show me the result.

## Your Environment

- latest
- latest
- best

**Comment by vicsn** [comment]
Thank you for sharing! This is a general blockchain UX issue, because after broadcasting, the transaction might fail asynchronously because it is:
- Rejected (insufficient fee)
- Aborted (malformed)
- Existing (double spend)

One potential solution is to add a flag to snarkOS which allows nodes to indicate they want to cache and serve failed transactions to users via the RPC endpoints: `--failed_txs_cache_size <int>`.

Let me know if you have any more thoughts on this, and if you agree we close this issue and instead make a "feature" issue for nodes to return the failure reason.

**Comment by arosboro** [comment]
Hi @vicsn, sure we can make it a feature issue, does that require closing and re-submitting, or can it be edited?  In general it would be helpful to see which of the three scenarios users are met with when trying to deploy and having these issues.

**Comment by vicsn** [comment]
I think closing this and resubmitting would be cleanest. If we'd implement this maybe we can give even more granular information, e.g. why it is malformed.
